const NUMBER_OF_QUESTIONS = 10
const TIME_FOR_EACH_QUESTION = 15
const TIME_INTERVAL_BETWEEN_QUESTIONS = 1500

export default {
    NUMBER_OF_QUESTIONS,
    TIME_FOR_EACH_QUESTION,
    TIME_INTERVAL_BETWEEN_QUESTIONS
}