const NUMBER_OF_QUESTIONS = 10
const TIME_FOR_EACH_QUESTION = 15
const TIME_INTERVAL_BETWEEN_QUESTIONS = 1500
const SHARE_LINK_TITLE = "Play football player transfer quiz at"
const APP_ID = "2893375807395705"

export default {
    NUMBER_OF_QUESTIONS,
    TIME_FOR_EACH_QUESTION,
    TIME_INTERVAL_BETWEEN_QUESTIONS,
    SHARE_LINK_TITLE,
    APP_ID
}