module.exports = {
    "arsenal": require("../images/team_icon/arsenal.png"),
    "aston villa": require("../images/team_icon/aston villa.png"),
    "bournemouth": require("../images/team_icon/bournemouth.png"),
    "brighton": require("../images/team_icon/brighton.png"),
    "burnley": require("../images/team_icon/burnley.png"),
    "chelsea": require("../images/team_icon/chelsea.png"),
    "crystal palace": require("../images/team_icon/crystal palace.png"),
    "everton": require("../images/team_icon/everton.png"),
    "leicester": require("../images/team_icon/leicester.png"),
    "liverpool": require("../images/team_icon/liverpool.png"),
    "man city": require("../images/team_icon/man city.png"),
    "man united": require("../images/team_icon/man united.png"),
    "newcastle": require("../images/team_icon/newcastle.png"),
    "norwich": require("../images/team_icon/norwich.png"),
    "sheffield united": require("../images/team_icon/sheffield united.png"),
    "southampton": require("../images/team_icon/southampton.png"),
    "tottenham": require("../images/team_icon/tottenham.png"),
    "watford": require("../images/team_icon/watford.png"),
    "west ham": require("../images/team_icon/west ham.png"),
    "wolves": require("../images/team_icon/wolves.png"),
    "augsburg": require("../images/team_icon/augsburg.png"),
    "bayern munich": require("../images/team_icon/bayern munich.png"),
    "dortmund": require("../images/team_icon/dortmund.png"),
    "ein frankfurt": require("../images/team_icon/ein frankfurt.png"),
    "fc koln": require("../images/team_icon/fc koln.png"),
    "fortuna düsseldorf": require("../images/team_icon/fortuna düsseldorf.png"),
    "freiburg": require("../images/team_icon/freiburg.png"),
    "hertha": require("../images/team_icon/hertha.png"),
    "hoffenheim": require("../images/team_icon/hoffenheim.png"),
    "leverkusen": require("../images/team_icon/leverkusen.png"),
    "m'gladbach": require("../images/team_icon/m'gladbach.png"),
    "mainz": require("../images/team_icon/mainz.png"),
    "paderborn": require("../images/team_icon/paderborn.png"),
    "rasenballsport leipzig": require("../images/team_icon/rasenballsport leipzig.png"),
    "schalke 04": require("../images/team_icon/schalke 04.png"),
    "union berlin": require("../images/team_icon/union berlin.png"),
    "werder bremen": require("../images/team_icon/werder bremen.png"),
    "wolfsburg": require("../images/team_icon/wolfsburg.png"),
    "atalanta": require("../images/team_icon/atalanta.png"),
    "bologna": require("../images/team_icon/bologna.png"),
    "brescia": require("../images/team_icon/brescia.png"),
    "cagliari": require("../images/team_icon/cagliari.png"),
    "fiorentina": require("../images/team_icon/fiorentina.png"),
    "genoa": require("../images/team_icon/genoa.png"),
    "inter": require("../images/team_icon/inter.png"),
    "juventus": require("../images/team_icon/juventus.png"),
    "lazio": require("../images/team_icon/lazio.png"),
    "lecce": require("../images/team_icon/lecce.png"),
    "milan": require("../images/team_icon/milan.png"),
    "napoli": require("../images/team_icon/napoli.png"),
    "parma calcio 1913": require("../images/team_icon/parma calcio 1913.png"),
    "roma": require("../images/team_icon/roma.png"),
    "sampdoria": require("../images/team_icon/sampdoria.png"),
    "sassuolo": require("../images/team_icon/sassuolo.png"),
    "spal 2013": require("../images/team_icon/spal 2013.png"),
    "torino": require("../images/team_icon/torino.png"),
    "udinese": require("../images/team_icon/udinese.png"),
    "verona": require("../images/team_icon/verona.png"),
    "amiens": require("../images/team_icon/amiens.png"),
    "angers": require("../images/team_icon/angers.png"),
    "bordeaux": require("../images/team_icon/bordeaux.png"),
    "brest": require("../images/team_icon/brest.png"),
    "dijon": require("../images/team_icon/dijon.png"),
    "lille": require("../images/team_icon/lille.png"),
    "lyon": require("../images/team_icon/lyon.png"),
    "marseille": require("../images/team_icon/marseille.png"),
    "metz": require("../images/team_icon/metz.png"),
    "monaco": require("../images/team_icon/monaco.png"),
    "montpellier": require("../images/team_icon/montpellier.png"),
    "nantes": require("../images/team_icon/nantes.png"),
    "nice": require("../images/team_icon/nice.png"),
    "nimes": require("../images/team_icon/nimes.png"),
    "paris sg": require("../images/team_icon/paris sg.png"),
    "rennes": require("../images/team_icon/rennes.png"),
    "st etienne": require("../images/team_icon/st etienne.png"),
    "stade de reims": require("../images/team_icon/stade de reims.png"),
    "strasbourg": require("../images/team_icon/strasbourg.png"),
    "toulouse": require("../images/team_icon/toulouse.png"),
    "alaves": require("../images/team_icon/alaves.png"),
    "ath bilbao": require("../images/team_icon/ath bilbao.png"),
    "ath madrid": require("../images/team_icon/ath madrid.png"),
    "barcelona": require("../images/team_icon/barcelona.png"),
    "betis": require("../images/team_icon/betis.png"),
    "celta vigo": require("../images/team_icon/celta vigo.png"),
    "eibar": require("../images/team_icon/eibar.png"),
    "espanol": require("../images/team_icon/espanol.png"),
    "getafe": require("../images/team_icon/getafe.png"),
    "granada": require("../images/team_icon/granada.png"),
    "leganes": require("../images/team_icon/leganes.png"),
    "levante": require("../images/team_icon/levante.png"),
    "mallorca": require("../images/team_icon/mallorca.png"),
    "osasuna": require("../images/team_icon/osasuna.png"),
    "real madrid": require("../images/team_icon/real madrid.png"),
    "sevilla": require("../images/team_icon/sevilla.png"),
    "sociedad": require("../images/team_icon/sociedad.png"),
    "valencia": require("../images/team_icon/valencia.png"),
    "valladolid": require("../images/team_icon/valladolid.png"),
    "villarreal": require("../images/team_icon/villarreal.png"),
    "ado den haag": require("../images/team_icon/ado den haag.png"),
    "ajax": require("../images/team_icon/ajax.png"),
    "az alkmaar": require("../images/team_icon/az alkmaar.png"),
    "fc emmen": require("../images/team_icon/fc emmen.png"),
    "fc groningen": require("../images/team_icon/fc groningen.png"),
    "fc twente": require("../images/team_icon/fc twente.png"),
    "fc utrecht": require("../images/team_icon/fc utrecht.png"),
    "feyenoord": require("../images/team_icon/feyenoord.png"),
    "fortuna sittard": require("../images/team_icon/fortuna sittard.png"),
    "pec zwolle": require("../images/team_icon/pec zwolle.png"),
    "psv eindhoven": require("../images/team_icon/psv eindhoven.png"),
    "rkc waalwijk": require("../images/team_icon/rkc waalwijk.png"),
    "sc heerenveen": require("../images/team_icon/sc heerenveen.png"),
    "sc heracles almelo": require("../images/team_icon/sc heracles almelo.png"),
    "sparta": require("../images/team_icon/sparta.png"),
    "vitesse": require("../images/team_icon/vitesse.png"),
    "vvv-venlo": require("../images/team_icon/vvv-venlo.png"),
    "willem ii": require("../images/team_icon/willem ii.png"),
    "aves": require("../images/team_icon/aves.png"),
    "belenenses": require("../images/team_icon/belenenses.png"),
    "benfica": require("../images/team_icon/benfica.png"),
    "boavista": require("../images/team_icon/boavista.png"),
    "braga": require("../images/team_icon/braga.png"),
    "f.c. paços de ferreira": require("../images/team_icon/f.c. paços de ferreira.png"),
    "famalicao": require("../images/team_icon/famalicao.png"),
    "fc porto": require("../images/team_icon/fc porto.png"),
    "gil vicente": require("../images/team_icon/gil vicente.png"),
    "guimaraes": require("../images/team_icon/guimaraes.png"),
    "maritimo": require("../images/team_icon/maritimo.png"),
    "moreirense": require("../images/team_icon/moreirense.png"),
    "portimonense": require("../images/team_icon/portimonense.png"),
    "rio ave": require("../images/team_icon/rio ave.png"),
    "santa clara": require("../images/team_icon/santa clara.png"),
    "sporting cp": require("../images/team_icon/sporting cp.png"),
    "tondela": require("../images/team_icon/tondela.png"),
    "vitoria setubal": require("../images/team_icon/vitoria setubal.png"),
    "atlanta united": require("../images/team_icon/atlanta united.png"),
    "chicago fire": require("../images/team_icon/chicago fire.png"),
    "colorado rapids": require("../images/team_icon/colorado rapids.png"),
    "columbus crew": require("../images/team_icon/columbus crew.png"),
    "dc united": require("../images/team_icon/dc united.png"),
    "fc cincinnati": require("../images/team_icon/fc cincinnati.png"),
    "fc dallas": require("../images/team_icon/fc dallas.png"),
    "houston dynamo": require("../images/team_icon/houston dynamo.png"),
    "inter miami": require("../images/team_icon/inter miami.png"),
    "l.a. galaxy": require("../images/team_icon/l.a. galaxy.png"),
    "los angeles fc": require("../images/team_icon/los angeles fc.png"),
    "minnesota united": require("../images/team_icon/minnesota united.png"),
    "montreal impact": require("../images/team_icon/montreal impact.png"),
    "nashville sc": require("../images/team_icon/nashville sc.png"),
    "new england rev.": require("../images/team_icon/new england rev..png"),
    "new york city": require("../images/team_icon/new york city.png"),
    "new york red bulls": require("../images/team_icon/new york red bulls.png"),
    "orlando city": require("../images/team_icon/orlando city.png"),
    "philadelphia union": require("../images/team_icon/philadelphia union.png"),
    "portland timbers": require("../images/team_icon/portland timbers.png"),
    "real salt lake": require("../images/team_icon/real salt lake.png"),
    "san jose earthquakes": require("../images/team_icon/san jose earthquakes.png"),
    "seattle sounders fc": require("../images/team_icon/seattle sounders fc.png"),
    "sporting kansas city": require("../images/team_icon/sporting kansas city.png"),
    "toronto fc": require("../images/team_icon/toronto fc.png"),
    "vancouver whitecaps": require("../images/team_icon/vancouver whitecaps.png"),
    "atletico go": require("../images/team_icon/atletico go.png"),
    "atletico mg": require("../images/team_icon/atletico mg.png"),
    "atletico pr": require("../images/team_icon/atletico pr.png"),
    "bahia": require("../images/team_icon/bahia.png"),
    "botafogo rj": require("../images/team_icon/botafogo rj.png"),
    "bragantino": require("../images/team_icon/bragantino.png"),
    "ceara": require("../images/team_icon/ceara.png"),
    "corinthians": require("../images/team_icon/corinthians.png"),
    "coritiba": require("../images/team_icon/coritiba.png"),
    "flamengo": require("../images/team_icon/flamengo.png"),
    "fluminense": require("../images/team_icon/fluminense.png"),
    "fortaleza": require("../images/team_icon/fortaleza.png"),
    "goias": require("../images/team_icon/goias.png"),
    "gremio": require("../images/team_icon/gremio.png"),
    "internacional": require("../images/team_icon/internacional.png"),
    "palmeiras": require("../images/team_icon/palmeiras.png"),
    "santos fc": require("../images/team_icon/santos fc.png"),
    "sao paulo": require("../images/team_icon/sao paulo.png"),
    "sport club do recife": require("../images/team_icon/sport club do recife.png"),
    "vasco da gama": require("../images/team_icon/vasco da gama.png"),
    "beijing guoan": require("../images/team_icon/beijing guoan.png"),
    "beijing renhe": require("../images/team_icon/beijing renhe.png"),
    "chongqing lifan": require("../images/team_icon/chongqing lifan.png"),
    "dalian yifang": require("../images/team_icon/dalian yifang.png"),
    "guangzhou evergrande": require("../images/team_icon/guangzhou evergrande.png"),
    "guangzhou r&f f.c.": require("../images/team_icon/guangzhou r&f f.c..png"),
    "hebei cffc": require("../images/team_icon/hebei cffc.png"),
    "henan jianye": require("../images/team_icon/henan jianye.png"),
    "jiangsu sainty": require("../images/team_icon/jiangsu sainty.png"),
    "shandong luneng": require("../images/team_icon/shandong luneng.png"),
    "shanghai east asia fc": require("../images/team_icon/shanghai east asia fc.png"),
    "shanghai greenland shenhua": require("../images/team_icon/shanghai greenland shenhua.png"),
    "shenzhen fc": require("../images/team_icon/shenzhen fc.png"),
    "tianjin teda": require("../images/team_icon/tianjin teda.png"),
    "tianjin tianhai": require("../images/team_icon/tianjin tianhai.png"),
    "wuhan zall": require("../images/team_icon/wuhan zall.png")
}